export const translations = {
  en: {
    checkmateComedian: 'Check Roast Ai',
    gameMode: 'Game Mode',
    playerVsPlayer: 'Player vs Player',
    playerVsBot: 'Player vs Bot',
    aiDifficulty: 'Select Bot Difficulty',
    easy: 'Easy',
    hard: 'Hard',
    roastIntensity: 'Roast Intensity',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    language: 'Language',
    english: 'English',
    urdu: 'Roman Urdu',
    generatingRoast: 'Generating roast...',
    turn: 'Turn',
    white: 'White',
    black: 'Black',
    newGame: 'New Game',
    startGame: 'Start Game',
    settings: 'Settings',
    initialRoast: 'Make a move... I dare you.',
    botRoast: "Thinking of a way to crush you... and your spirit.",
    hint: 'Hint',
  },
  ur: {
    checkmateComedian: 'Check Roast Ai',
    gameMode: 'Game Mode',
    playerVsPlayer: 'Player vs Player',
    playerVsBot: 'Player vs Bot',
    aiDifficulty: 'Select Bot Difficulty',
    easy: 'Easy',
    hard: 'Hard',
    roastIntensity: 'Roast Intensity',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    language: 'Language',
    english: 'English',
    urdu: 'Roman Urdu',
    generatingRoast: 'Roast tayyar kiya ja raha hai...',
    turn: 'Bari',
    white: 'Safaid',
    black: 'Siyah',
    newGame: 'Naya Khel',
    startGame: 'Khel Shuru Karein',
    settings: 'Settings',
    initialRoast: 'Ek chaal chalo... agar himmat hai to.',
    botRoast: "Tumhe kuchalne ka tareeqa soch raha hun... aur tumhari rooh ko bhi.",
    hint: 'Ishara',
  },
};
